@startuml
actor User

rectangle "Color Labs" {

    User --> (Login)

   

    (Login) --> (Add Color) 
    (Login) --> (Search Color) 
    (Search Color) --> (Logout) 
    (Add Color) --> (Logout)

}
@enduml
