name: Lint

on:
  push:
    branches: [ main, ci-lint-setup ]
  pull_request:
    branches: [ main, ci-lint-setup ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
	working-directory: ./

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"
	working-directory: ./
        continue-on-error: true

      - name: Run Stylelint
        run: npx stylelint "**/*.css"
	working-directory: ./
        continue-on-error: true

      - name: Run ESLint
        run: npx eslint "**/*.js"
	working-directory: ./
        continue-on-error: true
